### PR TITLE
Shuvojit nandi patch 1

### PR DESCRIPTION
**Pull request by ShuvojitNandi**
## Description

I have added a github_actions.yml file to the directory  claytontv/.github/
This workflow creates a github action which automates testing ( #50 )

Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How has this been tested?

Since its a github action workflow the only way to test it, is to push it to the remote repo and look at the actions tab for success or failure. In my latest yaml code it passed all the test and successfully ran the test on catalogue/tests.

## Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## What should reviewers look for?

In the process of writing a workflow I have added some code to the pipfile. Please review it.

### CODE REVIEW

**Comment by thatgardnerone** [comment]
Thanks for the PR @ShuvojitNandi! It looks reasonable, so I'll test it's suitable and get that merged.
Out of curiosity, where did you come across our project, and what would your interest be in future contributions?

**Review by thatgardnerone — APPROVED** [review]

**Comment by ShuvojitNandi** [comment]
I was searching through github for some beginner level issues and came accross your reporsitory. I am a fourth year comp sci student at Memorial University and I am building up my github profile for internships and job applications. 
I would like to contribute to the project in future. Right now there is no specific interest, I am open to learn and work on anything.

**Comment by thatgardnerone** [comment]
> I was searching through github for some beginner level issues and came accross your reporsitory. I am a fourth year comp sci student at Memorial University and I am building up my github profile for internships and job applications. 
> 
> I would like to contribute to the project in future. Right now there is no specific interest, I am open to learn and work on anything.
> 
> 

Your efforts are very welcome!
We're a Christian team from the UK building out a SaaS for our church, if you haven't gathered that from the repo so far. We'll add more info to the README shortly. 
It's a pleasure to make your acquaintance, and if you'd like to continue to expand your GitHub profile by working on this project with us, I'd be happy to chat to you further. My email address is on my GitHub profile if you want to get in touch directly. 
Otherwise, please feel free to browse the project board and continue creating PRs 💪 thanks again!

**Comment by ShuvojitNandi** [comment]
Thanks! I appreciate it..

**Pull request merged**
